[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -v --tb=short --html=reports/report.html --self-contained-html

markers =
    chromium: run test only on chromium
    firefox: run test only on firefox
    webkit: run test only on webkit
    smoke: smoke tests
    regression: full regression suite

log_cli = true
log_cli_level = INFO